### ISSUE TITLE
how to use my own data to evaluate your code

### ISSUE THREAD

**Issue by john09282922** [royson/tpsr#1]
Hi, I am trying to use this code for my image with low resolution to enlarge high resolution.
But, when I typed in python evaluate.py --model pretrained/TPSR_D2X4.pt --ground_truth 'my file name'
it is not working. i changed png --> jpg in your code. and make same file name in input folder.
Help me 

Thanks,

**Comment by john09282922** [comment]
I fixed. But I just wonder do I make same size for input and GT?

**Comment by royson** [comment]
Hi, apologies for the late response. The input spatial size should be (H/s,W/s) if the GT image is of spatial size (H,W) where s is the scaling factor. We have only tested with scaling factors of 2 and 4.

**Comment by john09282922** [comment]
Hi, Thanks for your answer.
I have image that looks like pixels broken... very low resolution...
It is very small size 100 x75 for low resolution(96 DPI), and GT is 224 x 168 (96DPI).. I think when scaling up, it is not working well... If you have some idea, please give me an advice... I am using scface data set..

**Comment by royson** [comment]
Hi, I'm sorry to hear that. Our model is proposed for devices with extremely limited compute. If you are not limited by that, perhaps try a larger-scale method. 
Our model is also trained using .PNG files so perhaps an approach that specifically targets JPG compression artifacts would work in your case. Hope this helps.

**Comment by john09282922** [comment]
Thank you for replying me. I am focusing on models for edge device. I think this model is pretty closing. Do I make sure use large data set to make super resolution? could u recommend any papers related to edge-device or higher recommending recent papers with super resolution?

**Comment by royson** [comment]
Ah, I see the topic is diverging from TPSR so I am closing this issue but feel free to drop me an email at dsrl2@cam.ac.uk and I'll see what I can do
